### ISSUE TITLE
Where is the installer for macOS?

### ISSUE THREAD

**Issue by gduranon** [efoxbr/megacubo#1]
The website explains Megacubo 2018 works in Windows, Linux and Mac, but the Mac installer is not found anywhere.

Is it already available?

Kind regards

**Comment by rgarciaaren** [comment]
I think it is us (The Mac Users) who should take the source code and create a .dmg, or .pkg or compile it, or whatever. Until now I don't know how to do it, I'll search in the web, sooner o later I'll find the way.

**Comment by efoxbr** [comment]
Mac installer finally added, starting with version 15.4.8.

https://github.com/efoxbr/megacubo/releases

**Comment by efoxbr** [comment]
Mac installer updated.

I'm not a Mac user, so the installer is very primitive. 

For anyone who wants to help to improve the installer, I've upload the DMG build script here: https://github.com/efoxbr/megacubo-dmg-installer

:)
