### ISSUE TITLE
I want to add an .m3u file, I guess it doesn't exist. Can you add or show if any?

### ISSUE THREAD

**Issue by DogancanYr** [efoxbr/megacubo#12]

**Comment by efoxbr** [comment]
Hi @DogancanYr, if you don't have a m3u file to add, you can go to "IPTV Lists > Communitary mode" and mark the "Enable" option.

It will make the program automatically get lists shared by other users.

After mark "Enable", you can enter the "Legal IPTV" section, there you find country specific lists too.
