### ISSUE TITLE
Load local m3u file

### ISSUE THREAD

**Issue by 1aspirin1** [efoxbr/megacubo#13]
Hi,

Is it possible to load iptv list I have saved as a m3u file on my pc?

Thanks in advance!

**Comment by efoxbr** [comment]
Hi @1aspirin1, yes, from version 16.3.3 it is possible. Just click on IPTV Lists > Add List (or My Lists) > Add M3U file.

**Comment by 1aspirin1** [comment]
Thank you for your answer. Working fine in 16.3.4.
Great work on the app, I am new to it but so far it is looking really good!
