### ISSUE TITLE
IPTV Lists > m3u file > TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by skaox** [efoxbr/megacubo#14]
Hi,

m3u file is added but when trying to access it : TypeError: Cannot read property 'length' of null

![megacubo_error_m3u_list](https://user-images.githubusercontent.com/22966700/180596852-523e8c33-78c8-4579-b938-b423c389cb68.jpg)

Terminal :

`/opt/megacubo/megacubo`

`[170985:171011:0723/043504.103255:ERROR:bus.cc(396)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")`

`[170985:170985:0723/043504.104414:ERROR:component_loader.cc(164)] Failed to parse extension manifest.
Error creating proxy: Unknown or unsupported transport “disabled” for address “disabled:” (g-io-error-quark, 13)`

`(megacubo:170985): dconf-WARNING **: 04:35:15.418: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”`

`Received signal 11 SEGV_MAPERR 000000000060`

`#0 0x7fb83c36cef9 <unknown>
  r8: 00000d1a3d6007f1  r9: 000002a0297804d1 r10: 0000000000000001 r11: 000002a029784d21
 r12: 00007ffceff7cdd0 r13: 00007ffceff7ce58 r14: 00007fb833d262f8 r15: 0000000000000000
  di: 0000000000000000  si: 0000000000000000  bp: 00007ffceff7ccf0  bx: 0000000000000000
  dx: 0000000000030001  ax: 0000000000000001  cx: 0000000000000000  sp: 00007ffceff7ccc0
  ip: 00007fb8326c6981 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000060`

`[end of stack trace]`

`Calling _exit(1). Core file will not be generated.`

Same result with all playlists tested and working with other iptv software.

Thank you in advance

Ubuntu Mate 20.04 amd64

**Comment by efoxbr** [comment]
Hi @skaox, in which version of Megacubo is this error occurring?

**Comment by skaox** [comment]
Megacubo_16.6.3_linux_x64.tar.gz
&
Megacubo_16.6.3_x86_64.AppImage

 
Same thing 16.5.9 -> 16.6.3.


Also tested with a fresh Ubuntu Mate 22.04 amd64 it's even worse

after Add list (m3u file) no message (lists updated, list added)

bugged need to close Megacubo, reopen it and same message :

TypeError: Cannot read property 'length' of null

**Comment by efoxbr** [comment]
Thanks for letting me know @skaox, this bug is now fixed in version 16.6.4.
