### ISSUE TITLE
v16.6.7 broadcast server overloaded

### ISSUE THREAD

**Issue by skaox** [efoxbr/megacubo#15]
Hi,

bug on lists searching was really annoying but now with 1.6.7 all channels are not working :

![megacubo_error_server_overloaded](https://user-images.githubusercontent.com/22966700/186301001-766cb788-b57e-4fc8-99fe-b38273e1136f.png)

Same list no problem with 1.6.4 and 1.6.5.

Thank you in advance.

**Comment by efoxbr** [comment]
Hi @skaox, thanks for bringing my attention to this. The pump() method was being called too early in [this file](https://github.com/efoxbr/megacubo/commit/51dccc610889082b2d7ad6e51512a2423100048c#diff-7dac717cf5bb693b9717ce46167cec7c37f7ef813f0ca7d352ec7fe780f78fd9), bug fixed in version 16.6.8.
