### ISSUE TITLE
spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by drtiwarir** [efoxbr/megacubo#16]
I am trying to play a live tv m3u playlist, but getting error spawn ffmpeg ENOENT, I have installed Megacubo on Mac Mini.
It works well in Kodi
Please help

Regards

**Comment by efoxbr** [comment]
@drtiwarir This message means that the FFmpeg executable was not found. It would need to be in the Contents/Resources/app.nw/ffmpeg folder inside the DMG.

I tested Megacubo_16.7.3_macos.dmg from the releases section on macOS Mojave and it worked fine. Does the error occur in this same DMG file?

**Comment by drtiwarir** [comment]
I tried again today, but the same error, I am having macOS Monterey version 12.6
May be it needs update

**Comment by efoxbr** [comment]
@drtiwarir Possibly the problem is the version of FFmpeg used in the build. As soon as I solve issue #28 I will take care of this, until then, I will close this one in favor of the mentioned issue, more details there.

**Comment by efoxbr** [comment]
Hello @drtiwarir, I have now added the DMG file in the [version 17.2.6 release](https://github.com/efoxbr/megacubo/releases/tag/v17.2.6) with this bugfix.
