### ISSUE TITLE
ISSUE: Not able to add M3U list.

### ISSUE THREAD

**Issue by heyvoon** [efoxbr/megacubo#20]
Hi,

I just installed the Megacubo but when trying to add my M3U via URL with my Username/Password it doesn't work. It keeps saying "Processing..." and nothing happens. The M3U is not added at the end. 

![image](https://user-images.githubusercontent.com/3281265/207654492-de303318-af0e-49ae-a53e-78d8963db2ba.png)

![image](https://user-images.githubusercontent.com/3281265/207655092-7ac02030-6638-4aec-8de9-b653ec3f0140.png)

Thank you in advance. It's a shame that it doesn't work. It looks beatiful though!

**Comment by efoxbr** [comment]
Hi @heyvoon, this should be fixed as of release [v16.7.6](https://github.com/efoxbr/megacubo/tree/v16.7.6). If the problem persists, please let us know.

**Comment by heyvoon** [comment]
Hi @efoxbr, it seems like the problem still persists when trying to add the M3U from my service provider with the URL below... (Username and password removed from URL 😉)
http://line.porschetv.net:80/get.php?username=MYUSER&password=MYPASS&output=ts&type=m3u_plus
PS. The above works without issues on IPTV Smarters, VLC and etc but not on Megacubo. 

![image](https://user-images.githubusercontent.com/3281265/210217677-9a9207fc-43f5-4ef4-b729-9c5275ff7c4d.png)

**Comment by andekande** [comment]
I get the same error with version 16.7.7
I am loading a local file with a single entry though.
It used to work couple of versions before.
`
#EXTM3U
#EXTINF:-1 tvg-id="None" tvg-name="Channel 1" group-title="Test",Channel 1
#EXTVLCOPT:http-user-agent=APP/1.0
http://127.0.0.1:8008/a/b/c/123.ts|User-Agent=APP/1.0
`

**Comment by efoxbr** [comment]
>
> Hi @efoxbr, I've downloaded the latest version as recommended but it seems like the problem still persists when trying to add the M3U from my service provider with the URL below... [...] Manually downloading the m3u file (104MB) and adding it to Megacubo works [...]
> 
@heyvoon Please test with version 16.7.8, the list size limit is now 200MB (was 28MB in version 16.7.6). If it persists let me know.

> 
> By the way, I have `"enable-console": true` but F12 does not bring up DevTools. Is there any way can I open the browser console to see log messages?
> 
@andekande To access the DevTools on Megacubo you must replace the files of the normal NW.js version with the SDK version.

To do so, [download the NW.js 0.37.4 SDK Build](https://dl.nwjs.io/v0.37.4/) (on the same CPU architecture), go to the installation folder and replace all the files with those in the downloaded file EXCEPT the ffmpeg.dll file (or lib/libffmpeg.so on Linux), keep the original one for these.

https://dl.nwjs.io/v0.37.4/

**Comment by heyvoon** [comment]
@efoxbr Did the following on my linux box...

- Uninstall old version completely and removed the config folder.
- Install the new version 16.7.8
- Open application and after about a minute the application now closes by itself.

**Comment by efoxbr** [comment]
> Open application and after about a minute the application now closes by itself.

@heyvoon Bug fixed in version 16.7.9.

**Comment by lexterror** [comment]
its not fixed in either Android or Linux. Im unable to add an m3u file with 2000 channels... it just does not let me add the file.

**Comment by lexterror** [comment]
Please fix
