### ISSUE TITLE
Custom User Agent

### ISSUE THREAD

**Issue by andekande** [efoxbr/megacubo#21]
Feature Request: In addition to the built in string, allow the user to set one.
Reason: Servers may require a certain content (usually App string) as part of user authentication.

Alternative: Parse the User-Agent from the m3u. Here is the format VLC understands:
```
#EXTINF:-1 tvg-name="TV Channel 1",TV Channel 1
#EXTVLCOPT:http-user-agent=MYAPP/1.0
http://a.b.c.d:8008/stream.ts|User-Agent=MYAPP/1.0
```

![grafik](https://user-images.githubusercontent.com/1636928/208312956-6d2e922c-1126-4c0e-a872-4acb84363dee.png)

**Comment by efoxbr** [comment]
Hi @andekande, thanks for pointing this out. The commit [e5eebb7](https://github.com/efoxbr/megacubo/commit/e5eebb78d550eb0a9df743a5e7217094548cf565) (release [v16.7.6](https://github.com/efoxbr/megacubo/tree/v16.7.6)) now brings this improvement. App will recognize both proposed syntaxes.

**Comment by andekande** [comment]
Wow, that was a quick implementation.
However, list parsing seems to be broken now as I cant add my m3u.
