### ISSUE TITLE
Custom User Agent

### ISSUE THREAD

**Issue by andekande** [efoxbr/megacubo#23]
From comment in https://github.com/efoxbr/megacubo/issues/21#issuecomment-1371418302

Getting 'media error' also in 16.8.0 when trying to play from stream that requires a specific http header.

I Did some code analysis and found this:
https://github.com/efoxbr/megacubo/commit/e5eebb78d550eb0a9df743a5e7217094548cf565#r95076585

> The derived classes never pass the new `data` object in, which renders getDefaultRequestHeaders() useless:
https://github.com/efoxbr/megacubo/blob/master/www/nodejs-project/modules/streamer/adapters/ts.js#L6
https://github.com/efoxbr/megacubo/blob/master/www/nodejs-project/modules/streamer/adapters/aac.js#L6
https://github.com/efoxbr/megacubo/blob/master/www/nodejs-project/modules/streamer/utils/downloader.js#L15
https://github.com/efoxbr/megacubo/blob/master/www/nodejs-project/modules/streamer/utils/proxy-base.js#L6

Further did overwrite files by SDK from https://dl.nwjs.io/v0.37.4/ to no effect. Still can't see a console. Shouldn't it be detected by chrome://inspect/#devices ?

**Comment by efoxbr** [comment]
Overwriting with the SDK files should give the option to open DevTools by pressing F12 or right clicking. The DevTools should also be accessible at: http://127.0.0.1:9000/

If it doesn't work let me know.

About UA, thanks for confirming. I had made a test M3U file to verify this and it really looks OK:

https://app.megacubo.net/test/test.m3u

Let me know if you notice any other problems.

P.S: Version 16.8.1 installers were updated few hours ago with commit v16.8.1-rev3.
