### ISSUE TITLE
EPG downloaded as xml.gz

### ISSUE THREAD

**Issue by andekande** [efoxbr/megacubo#24]
My EPG source is https://m3u4u.com/
A request to https://m3u4u.com/epg/a1b2c3d4e5 replies with these HTTP Headers:
```
content-type: application/x-gzip
content-length: 1758815
content-disposition: attachment; filename=EPG-Guide-20230124172906.xml.gz; filename*=UTF-8''EPG-Guide-20230124172906.xml.gz
```
So there is no `content-encoding` but `content-disposition`.
I believe that compression detection is not yet covered for that case in downloader module:
https://github.com/efoxbr/megacubo/blob/master/www/nodejs-project/modules/download/download.js#L406
https://github.com/efoxbr/megacubo/blob/master/www/nodejs-project/modules/download/download.js#L634
Where it should detect 'gzip'.

The EPG module throws with BAD_FORMAT: https://github.com/efoxbr/megacubo/blob/master/www/nodejs-project/modules/epg/epg.js#L238

An easy fix would be to check for '.gz' filename not only in url but also `content-disposition` header here:
https://github.com/efoxbr/megacubo/blob/master/www/nodejs-project/modules/download/download.js#L412

**Comment by efoxbr** [comment]
Hi @andekande, thanks for pointing out the bug. Could you test again with version 16.8.1 from the link below to confirm that this bug is resolved?

https://github.com/efoxbr/megacubo/releases/v16.8.1

**Comment by andekande** [comment]
Thank you @efoxbr.
EPG loaded succesfully !!!
Also User-Agent is transmitted (see #23) !!!
Your works makes me super happy. :+1: :clap: :tv:

**Comment by efoxbr** [comment]
@andekande Thanks for confirming. I had made a test M3U file to verify this and it really looks OK:

https://app.megacubo.net/test/test.m3u

Let me know if you notice any other problems.
