### ISSUE TITLE
duplicated channels

### ISSUE THREAD

**Issue by andekande** [efoxbr/megacubo#25]
After updating to 16.8.1, my *remote* playlist gets read upon application start as usual.
However, this time I have all the contained channels as multiple duplicates.
The duplicates (~140) can't be played and no EPG can be matched.
UI message is "path not found".

When re-adding the list I get `Type Error: cannot read property of undefined` either when loading remote lists or local lists. However, the list is still loaded with a bunch of duplicates.

**Comment by efoxbr** [comment]
@andekande Today I released version 16.8.4 to fix this bug. Could you please test with it?

**Comment by andekande** [comment]
Thanks a lot. The issue with duplicated channels is resolved. Even without manual removal of playlist.

What remains is the error when adding a playlist, remote or local.

**Comment by efoxbr** [comment]
@andekande Solved a few versions ago, sorry to be responding so late.
