### ISSUE TITLE
channel sort order

### ISSUE THREAD

**Issue by andekande** [efoxbr/megacubo#27]
I am using a m3u playlist that has channel names like this:
```
tvg-name="TV CHANNEL 1",TV CHANNEL 1
tvg-name="TV CHANNEL1 FHD",TV CHANNEL1 FHD
tvg-name="TV CHANNEL 2",TV CHANNEL 2
tvg-name="TV CHANNEL 10",TV CHANNEL 10
```

In the User-Interface the sorting is:
- TV CHANNEL 1
- TV CHANNEL 10
- TV CHANNEL 2
- TV CHANNEL1 FHD

More naturally would be:
- TV CHANNEL 1
- TV CHANNEL1 FHD
- TV CHANNEL 2
- TV CHANNEL 10

I'd like to propose to consider numerical sorting instead of alphabetical, independent of the language.
Thank You.

Here is some background for Javascript:
- https://javascript.plainenglish.io/revisiting-natural-sorting-in-javascript-68b8e8c6f2af
- https://stackoverflow.com/questions/2802341/natural-sort-of-alphanumerical-strings-in-javascript

**Comment by efoxbr** [comment]
Hi @andekande, feature has been implemented.

In addition to naturally sorting, the current version seeks to make better use of the EPG data, if it is enabled, then the order can be affected by the name of the current TV show in each channel.

This behavior can be changed in Options > Manage channel list > Channel list sorting. The options are:

- Focus on TV shows - Display channels with available EPG first.

- Focus on channels with TV show images - First displays channels with available EPG and current program image.

- Focus on channels - Displays channels independently of the EPG.

Thanks for the idea, if you have any suggestions for improvement just let me know.
