### ISSUE TITLE
GlibC fail error 

### ISSUE THREAD

**Issue by alvarorichard** [efoxbr/megacubo#32]
Some time ago, every time I install or update the program, I always encounter an error related to the glibc library. The glibc is working correctly on my system, but nevertheless, this error keeps appearing. I am using Arch Linux, and this error only occurs during installation using a script.
```bash
 The following error is displayed:
Copying new files ...
mkdir: cannot create directory '/opt/megacubo': File exists
mkdir: cannot create directory '/root/.cache/megacubo-1432/': File exists
./install.sh: line 33: type: rsync: not found
Copying new files ... OK
Creating shortcut...
./install.sh: line 40: /root/.local/share/applications/megacubo.desktop: No such file or directory
Creating shortcut ... OK
Adjusting permissions...
chmod: cannot access '/root/.local/share/applications/megacubo.desktop': No such file or directory
Adjusting permission ... OK
Megacubo installed!
GLIBC ... FAIL
!!! You'll need to install/fix GLIBC on your system to run Megacubo. !!!
Megacubo installed at: /opt/megacubo
To also install special features (Premium) to record and cast to Google Chromecast, run the command below:
wget -qO- https://megacubo.tv/installpremium.sh | bash"
```

**Comment by efoxbr** [comment]
Hi @alvarorichard, the error may just be in the checking. Does the app work normally ignoring the error message?

**Comment by alvarorichard** [comment]
app works good

**Comment by efoxbr** [comment]
@alvarorichard From the next release (17.2.9) this error message will just be a informative notification.

Currently the install script checks for GLIBC this way:

    LDDOUTPUT=`ldd --version`
    if [[ "$LDDOUTPUT" == *GLIBC* ]]
    then
    	echo "GLIBC ... OK"
    else
    	echo "GLIBC ... FAIL"
    fi

I haven't found a better way to detect if GLIBC is OK, if anyone has suggestions, they are welcome.
