### ISSUE TITLE
[bug] my url doesn't work on megacubo

### ISSUE THREAD

**Issue by fallsdevil** [efoxbr/megacubo#33]
I wanted to test this software to use my IPTV on my Windows, but when I add my URL, username and password, whenever I open any channel, after loading the message "unauthorized" or "no transmission found" appears, one of the warnings says My address may be blocked, which I don't think it is, because another app on my Android is working perfectly.

**Comment by efoxbr** [comment]
Hi @fallsdevil , there have been some recent changes in this direction. Could you confirm if the problem persists with version 17.3.1 or if it has been fixed?
