### ISSUE TITLE
Formato MPD no funciona

### ISSUE THREAD

**Issue by wuniversales** [efoxbr/megacubo#37]
Los canales MPD no son reproducidos por la aplicación.
Tenéis un canal MPD en la siguiente lista.
`https://www.tdtchannels.com/lists/tv_mpd.m3u8`
Saludos

**Comment by efoxbr** [comment]
Hola @wuniversales, soporte DASH implementado con Dash.js desde la versión 17.3.3.

https://github.com/efoxbr/megacubo/releases/latest
