### ISSUE TITLE
User Swarm Video as  a freee high availability option

### ISSUE THREAD

**Issue by mullerivan** [efoxbr/megacubo#4]
How do i  can include swarm.video as it is a proper p2p tracker for  million viewers?

**Comment by mullerivan** [comment]
https://swarm.video/#/home

**Comment by efoxbr** [comment]
Hi @mullerivan, that should be implemented on the file:

[/assets/js/playback/internal-proxy-hls.js](https://github.com/efoxbr/megacubo/blob/master/assets/js/playback/internal-proxy-hls.js)

...replacing the p2p-media-loader-core module that is currently used in the program.

Note: As I understand it, swarm.video will add ads to the streams. 

> How to use it with out ADS:
> Contact us at info@swarm.video to allow your Channel into Our CORS filter and let start testing it for free

**Comment by mullerivan** [comment]
Thanks  bro!  i would like to give it  without  ads :)  will make a few  test and will be back to  you
