### ISSUE TITLE
AppImage format for Linux

### ISSUE THREAD

**Issue by joaopauloalbq** [efoxbr/megacubo#5]
The tar.gz format isn't friendly!
Distribute Megacube in the [AppImage](https://github.com/AppImage/AppImageKit) format plz

**Comment by efoxbr** [comment]
Good idea, I'll check that!

**Comment by efoxbr** [comment]
AppImages [added](https://github.com/efoxbr/megacubo/releases/tag/v15.4.8).

**Comment by joaopauloalbq** [comment]
Tested and works perfectly <3
